//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da VesselBuilder1.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG_MESH                 103
#define IDD_DIALOG_FOLLOWME             105
#define IDD_DIALOG_DOCK                 106
#define IDD_DIALOG_ANIM                 107
#define IDD_DIALOG_ANIMCOMP             108
#define IDD_DIALOG_ATT                  109
#define IDD_DIALOG_PROPELLANT           110
#define IDD_DIALOG_THRUSTERS            111
#define IDD_DIALOG_EXTEX                112
#define IDD_DIALOG_THRGRP               113
#define IDD_DIALOG_PARTICLES            114
#define IDD_DIALOG_TDPOINTS             115
#define IDD_DIALOG_SETTINGS             116
#define IDD_DIALOG_AIRFOILS             117
#define IDD_DIALOG_CTRLSURF             118
#define IDD_DIALOG_CAMERA               119
#define IDD_DIALOG_VCPOS                120
#define IDD_DIALOG_VCHUD                121
#define IDD_DIALOG_VCMFD                122
#define IDD_DIALOG_BEACONS              123
#define IDC_TREE1                       1001
#define IDC_SPIN_POSZ_S                 1005
#define IDC_SPIN_POSZ_L                 1006
#define IDC_SPIN_POSY_S                 1007
#define IDC_EDIT_MESHNAME               1008
#define IDC_BUTTON_LOADMESH             1009
#define IDC_EDIT_POSX                   1010
#define IDC_EDIT_TANKNAME               1010
#define IDC_EDIT_POSY                   1011
#define IDC_BUTTON_TANKNAMESET          1011
#define IDC_EDIT_POSZ                   1012
#define IDC_EDIT_TANKMAXMASS            1013
#define IDC_EDIT_THPOSY                 1013
#define IDC_SPIN_POSY_L                 1014
#define IDC_EDIT_TANKEFFIC              1014
#define IDC_SPIN_POSX_S                 1015
#define IDC_EDIT_TANKCURRMASS           1015
#define IDC_SPIN_POSX_L                 1016
#define IDC_EDIT_TANKISPRIMARY          1016
#define IDC_BUTTON_POS_SET              1017
#define IDC_CHECK_HIGHLIGHT_MSH         1019
#define IDC_EDIT_DIRX                   1020
#define IDC_EDIT_DIRY                   1021
#define IDC_EDIT_DIRZ                   1022
#define IDC_EDIT_THMAX                  1023
#define IDC_EDIT_THISPREF               1024
#define IDC_EDIT_THISP                  1025
#define IDC_EDIT_THPREF                 1026
#define IDC_BUTTON_DIR_SET              1027
#define IDC_EDIT_ROTX                   1028
#define IDC_BUTTON_THMAXSET             1028
#define IDC_EDIT_ROTY                   1029
#define IDC_BUTTON_THISPSET             1029
#define IDC_EDIT_ROTZ                   1030
#define IDC_BUTTON_THISPREFSET          1030
#define IDC_BUTTON_ROT_SET              1031
#define IDC_BUTTON_THPREFSET            1031
#define IDC_EDIT_GETANGLE               1038
#define IDC_STATIC_MSH1                 1039
#define IDC_STATIC_MSH2                 1040
#define IDC_STATIC_MSH3                 1041
#define IDC_STATIC_MSH4                 1042
#define IDC_STATIC_MSH5                 1043
#define IDC_STATIC_MSH6                 1044
#define IDC_STATIC_MSH7                 1045
#define IDC_STATIC_MSH8                 1046
#define IDC_STATIC_MSH9                 1047
#define IDC_STATIC_MSH10                1048
#define IDC_STATIC_MSH11                1049
#define IDC_STATIC_MSH12                1050
#define IDC_STATIC_MSH13                1051
#define IDC_STATIC_MSH14                1052
#define IDC_STATIC_MSH15                1053
#define IDC_BUTTON_DELETEMESHDEF        1054
#define IDC_STATIC_MSH23                1054
#define IDC_STATIC_MSH16                1055
#define IDC_STATIC_MSH24                1055
#define IDC_SPIN_ROLL                   1056
#define IDC_STATIC_MSH17                1056
#define IDC_STATIC_MSH25                1056
#define IDC_SPIN_PITCH                  1057
#define IDC_BUTTON_ADD                  1057
#define IDC_STATIC_MSH18                1057
#define IDC_STATIC_MSH26                1057
#define IDC_SPIN_YAW                    1058
#define IDC_EDIT_FMPOS                  1058
#define IDC_STATIC_MSH19                1058
#define IDC_STATIC_MSH27                1058
#define IDC_EDIT_FMDIR                  1059
#define IDC_STATIC_MSH20                1059
#define IDC_BUTTON_ADD2                 1059
#define IDC_STATIC_MSH36                1059
#define IDC_EDIT_ROT                    1060
#define IDC_EDIT_FMROT                  1060
#define IDC_STATIC_MSH21                1060
#define IDC_STATIC_MSH28                1060
#define IDC_STATIC_MSH37                1060
#define IDC_SLIDER_FMSPEED              1061
#define IDC_STATIC_MSH22                1061
#define IDC_STATIC_MSH29                1061
#define IDC_STATIC_MSH38                1061
#define IDC_SPIN_FMX                    1062
#define IDC_STATIC_MSH30                1062
#define IDC_SPIN_FMY                    1063
#define IDC_STATIC_MSH31                1063
#define IDC_STATIC_MSH32                1064
#define IDC_SPIN_FMZ                    1065
#define IDC_STATIC_MSH33                1065
#define IDC_SPIN_FMYAW                  1066
#define IDC_STATIC_MSH34                1066
#define IDC_STATIC_MSH35                1067
#define ID_COPY                         1068
#define ID_COPYVS                       1068
#define IDC_STATIC_MSH39                1068
#define ID_EXIT                         1069
#define IDC_STATIC_MSH40                1069
#define IDC_SPIN_FMPITCH                1070
#define IDC_STATIC_MSH41                1070
#define IDC_SPIN_FMROLL                 1071
#define IDC_STATIC_MSH42                1071
#define IDC_STATIC_MSH43                1072
#define IDC_SPIN2                       1073
#define IDC_STATIC_MSH44                1073
#define IDC_STATIC_MSH45                1074
#define IDC_STATIC_MSH46                1075
#define IDC_STATIC_MSH47                1076
#define IDC_STATIC_MSH48                1077
#define IDC_FMRESET                     1078
#define IDC_STATIC_MSH49                1078
#define IDC_BTN_MESHPASTEV              1079
#define IDC_STATIC_MSH50                1079
#define IDC_EDIT_DOCKPOSX               1080
#define IDC_STATIC_MSH51                1080
#define IDC_EDIT_DOCKPOSY               1081
#define IDC_STATIC_MSH52                1081
#define IDC_EDIT_DOCKPOSZ               1082
#define IDC_EDIT_DOCKDIRX               1083
#define IDC_EDIT_DOCKDIRY               1084
#define IDC_EDIT_DOCKDIRZ               1085
#define IDC_EDIT_DOCKROTX               1086
#define IDC_EDIT_DOCKROTY               1087
#define IDC_EDIT_DOCKROTZ               1088
#define IDC_SPIN_DOCKPITCH              1090
#define IDC_SPIN_DOCKYAW                1091
#define IDC_SPIN_DOCKROLL               1092
#define IDC_BUTTON_DELETEDOCKDEF        1093
#define IDC_BTN_DOCKPASTEV              1094
#define IDC_SPIN_DOCKPOSX               1095
#define IDC_SPIN_DOCKPOSY               1096
#define IDC_SPIN_DOCKPOSZ               1097
#define IDC_BUTTON_DOCKPOS_SET          1098
#define IDC_BUTTON_DOCKDIR_SET          1099
#define IDC_BUTTON_DOCKROT_SET          1100
#define IDC_CHECK_HIGHLIGHT_DOCK        1101
#define IDC_EDIT_DOCKNAME               1102
#define IDC_BUTTON_DOCKNAMESET          1103
#define IDC_COMBO_ANIMTYPE              1108
#define IDC_EDIT_ANIMDURATION           1109
#define IDC_EDIT_ANIMDEFSTATE           1110
#define IDC_EDIT_ANIMNAME               1111
#define IDC_COMBO_ANIMKEY               1112
#define IDC_BUTTON_ANIMDELETE           1113
#define IDC_BUTTON_ANIMADDCOMPROT       1114
#define IDC_BUTTON_ANIMDURATIONSET      1115
#define IDC_BUTTON_ANIMDEFSTATESET      1116
#define IDC_LIST_ANIMCOMPGRPSTOPICK     1117
#define IDC_BUTTON_ANIMNAMESET          1118
#define IDC_LIST_ANIMCOMPGRPSINANIM     1118
#define IDC_EDIT_ANIMNCOMPS             1119
#define IDC_BUTTON_ANIMADDCOMPTR        1120
#define IDC_BUTTON_ANIMADDCOMPSC        1121
#define IDC_EDIT_ANIMCOMPS0             1122
#define IDC_BUTTON_ANIMTESTANIM         1122
#define IDC_EDIT_ANIMCOMPS1             1123
#define IDC_COMBO_ANIMCOMPPARENT        1124
#define IDC_EDIT_ANIMCOMPTYPE           1125
#define IDC_EDIT_ANIMCOMPREFX           1126
#define IDC_EDIT_ANIMCOMPREFY           1127
#define IDC_EDIT_ANIMCOMPREFZ           1128
#define IDC_SLIDER_ANIMTEST             1129
#define IDC_COMBO_ANIMCOMPMESH          1129
#define IDC_BUTTON_ANIMCOMPSETGRPS      1130
#define IDC_EDIT_ANIMCOMPAXISX          1131
#define IDC_BUTTON_ANIMCOMPS0SET        1132
#define IDC_BUTTON_ANIMCOMPS1SET        1133
#define IDC_BUTTON_ANIMCOMPBACKGRPS     1134
#define IDC_EDIT_ANIMCOMPAXISY          1135
#define IDC_EDIT_ANIMCOMPAXISZ          1136
#define IDC_EDIT_ANIMCOMPANGLE          1137
#define IDC_BUTTON_ANIMCOMPREFSET       1138
#define IDC_BUTTON_ANIMCOMPAXISSET      1139
#define IDC_BUTTON_ANIMCOMPANGLESET     1140
#define IDC_BUTTON_ANIMCOMPPASTEV       1141
#define IDC_STATIC_ACREF                1142
#define IDC_STATIC_ACAX                 1143
#define IDC_STATIC_ACANGLE              1144
#define IDC_EDIT_ANIMCOMPNAME           1145
#define IDC_BUTTON_ANIMCOMPNAMESET      1146
#define IDC_BUTTON_ANIMCOMPDEL          1147
#define IDC_CHECK_ATTPARENT             1148
#define IDC_BUTTON_ANIMCOMPTIPSET       1148
#define IDC_CHECK_ATTHIGHLIGHT          1149
#define IDC_EDIT_ATTPOSX                1150
#define IDC_EDIT_ATTPOSY                1151
#define IDC_EDIT_ATTPOSZ                1152
#define IDC_BUTTON_ATTPOS_SET           1153
#define IDC_EDIT_ATTDIRX                1154
#define IDC_EDIT_ATTDIRY                1155
#define IDC_EDIT_ATTDIRZ                1156
#define IDC_BUTTON_ATTDIR_SET           1157
#define IDC_EDIT_ATTROTX                1158
#define IDC_EDIT_ATTROTY                1159
#define IDC_EDIT_ATTROTZ                1160
#define IDC_BUTTON_ATTROT_SET           1161
#define IDC_BTN_ATTPASTEV               1162
#define IDC_SPIN_ATTPITCH               1163
#define IDC_SPIN_ATTYAW                 1164
#define IDC_SPIN_ATTROLL                1165
#define IDC_BUTTON_CRDELATTDEF          1166
#define IDC_EDIT_ATTID                  1167
#define IDC_SPIN_ATTPOSX                1168
#define IDC_SPIN_ATTPOSY                1169
#define IDC_SPIN_ATTPOSZ                1170
#define IDC_STATIC_ANIMCOMPGRPS         1171
#define IDC_EDIT_ATTRANGE               1171
#define IDC_CHECK_ANIMCOMPARMTIP        1172
#define IDC_BUTTON_ATTRANGESET          1172
#define IDC_LIST_ANIMCOMPATTS           1173
#define IDC_BUTTON_TANKMAXMASSSET       1174
#define IDC_BUTTON_TANKEFFICSET         1175
#define IDC_BUTTON_TANKCURRMASSSET      1176
#define IDC_BUTTON_DELETETANK           1177
#define IDC_BUTTON_TANKPRIMARY          1178
#define IDC_BUTTON_THXP                 1179
#define IDC_BUTTON_THXM                 1180
#define IDC_BUTTON_THYP                 1181
#define IDC_BUTTON_THYM                 1182
#define IDC_BUTTON_THZP                 1183
#define IDC_BUTTON_THZM                 1184
#define IDC_COMBO_THPH                  1185
#define IDC_BUTTON_THEXWSET             1186
#define IDC_LIST_THPART                 1187
#define IDC_CHECK_THSHOW                1188
#define IDC_EDIT_THNAME                 1189
#define IDC_BUTTON_THNAMESET            1190
#define IDC_EDIT_THPOSX                 1191
#define IDC_EDIT_THPOSZ                 1192
#define IDC_BUTTON_THPOSSET             1193
#define IDC_SPIN_THPOSX                 1194
#define IDC_SPIN_THPOSY                 1195
#define IDC_SPIN_THPOSZ                 1196
#define IDC_EDIT_THDIRX                 1197
#define IDC_EDIT_THDIRY                 1198
#define IDC_EDIT_THDIRZ                 1199
#define IDC_BUTTON_THDIRSET             1200
#define IDC_BTN_THPASTEV                1201
#define IDC_BUTTON_DELETETH             1202
#define IDC_CHECK_THEX                  1203
#define IDC_COMBO_THEXTEX               1204
#define IDC_EDIT_THEXW                  1205
#define IDC_BUTTON_THEXLSET             1206
#define IDC_EDIT_THEXL                  1207
#define IDC_BUTTON_THTEST               1208
#define IDC_EDIT_EXTEXNAME              1209
#define IDC_BUTTON_THPARTSET            1209
#define IDC_BUTTON_EXTEXLOAD            1210
#define IDC_BUTTON_DELETEEXTEX          1212
#define IDC_LIST_THGRP                  1213
#define IDC_BUTTON_THRGRPDEFUNDEF       1215
#define IDC_EDIT_THGRP                  1216
#define IDC_CHECK_THGRPSHOW             1217
#define IDC_EDIT_PARTNAME               1218
#define IDC_BUTTON_PARTNAMESET          1219
#define IDC_EDIT_PARTSIZE               1220
#define IDC_EDIT_PARTRATE               1222
#define IDC_EDIT_PARTV0                 1223
#define IDC_EDIT_PARTSPREAD             1224
#define IDC_EDIT_PARTLIFETIME           1225
#define IDC_EDIT_PARTGROWTH             1226
#define IDC_EDIT_PARTATMSLOW            1227
#define IDC_COMBO_PARTLTYPE             1228
#define IDC_COMBO_PARTLVLMAP            1229
#define IDC_EDIT_PARTLMIN               1230
#define IDC_EDIT_PARTLMAX               1231
#define IDC_COMBO_PARTATMMAP            1232
#define IDC_EDIT_PARTAMIN               1233
#define IDC_EDIT_PARTAMAX               1234
#define IDC_COMBO_PARTTEX               1235
#define IDC_BUTTON_PARTSTORE            1236
#define IDC_BUTTON_DELETEPART           1237
#define IDC_BUTTON_PARTTEST             1238
#define IDC_EDIT_TDPPOSX                1238
#define IDC_EDIT_TDPPOSY                1239
#define IDC_EDIT_TDPPOSZ                1240
#define IDC_EDIT_TDPDAMP                1241
#define IDC_EDIT_TDPMU                  1242
#define IDC_EDIT_TDPMULNG               1243
#define IDC_EDIT_TDPSTIFF               1244
#define IDC_CHECK_TDPSHOWCUR            1245
#define IDC_EDIT_TDPCURSET              1246
#define IDC_COMBO_TDPCHANGEOVERANIM     1247
#define IDC_LIST_TDP                    1248
#define IDC_BUTTON_TDPADD               1249
#define IDC_BUTTON_TDPREMOVE            1250
#define IDC_BUTTON_TDPPASTEV            1251
#define IDC_BUTTON_TDPAPPLY             1252
#define IDC_CHECK_TDPENABLESET2         1253
#define IDC_BUTTON_TDPJ3P               1254
#define IDC_STATIC_TDPCHANGE            1255
#define IDC_BUTTON_TDPCLEARSET          1256
#define IDC_CHECK_TDPSHOW2              1257
#define IDC_CHECK_TDPSHOWSET            1257
#define IDC_EDIT_TDPHFG                 1258
#define IDC_EDIT_TDPRAD                 1259
#define IDC_CHECK_TDPTAILSITTER         1260
#define IDC_STATIC_TDPDEFGRP            1261
#define IDC_STATIC_TDPDEFHFG            1262
#define IDC_STATIC_TDPDEFRAD            1263
#define IDC_EDIT_SETEM                  1264
#define IDC_EDIT_SETPMIX                1265
#define IDC_EDIT_SETPMIY                1266
#define IDC_EDIT_SETPMIZ                1267
#define IDC_EDIT_SETCSX                 1268
#define IDC_EDIT_SETCSY                 1269
#define IDC_EDIT_SETCSZ                 1270
#define IDC_EDIT_SETSIZE                1271
#define IDC_EDIT_SETGGD                 1272
#define IDC_EDIT_SETRDX                 1273
#define IDC_EDIT_SETRDY                 1274
#define IDC_EDIT_SETRDZ                 1275
#define IDC_STATIC_VESSELNAME           1278
#define IDC_BUTTON_SETEMSET             1279
#define IDC_BUTTON_SETSIZESET           1280
#define IDC_EDIT_AIRFOILREFX            1280
#define IDC_BUTTON_SETPMISET            1281
#define IDC_EDIT_AIRFOILC               1281
#define IDC_BUTTON_SETCSSET             1282
#define IDC_EDIT_AIRFOILNAME            1282
#define IDC_BUTTON_SETGGDSET            1283
#define IDC_EDIT_AIRFOILS               1283
#define IDC_EDIT_AIRFOILA               1284
#define IDC_BUTTON_SETRDSET             1284
#define IDC_EDIT_AIRFOILREFY            1285
#define IDC_EDIT_AIRFOILREFZ            1286
#define IDC_BUTTON_AIRFOILREFSET        1287
#define IDC_BUTTON_AIRFOILNAMESET       1288
#define IDC_BUTTON_AIRFOILCSET          1289
#define IDC_BUTTON_AIRFOILASET          1290
#define IDC_BUTTON_AIRFOILSSET          1291
#define IDC_LIST_AIRFOILFUNC            1292
#define IDC_BUTTON_AIRFOILVIEWGRAPH     1293
#define IDC_BUTTON_DELAIRFOIL           1294
#define IDC_BUTTON_AIRFOILREMPOINT      1295
#define IDC_BUTTON_AIRFOILADDPOINT      1296
#define IDC_EDIT_AIRFOILCM              1297
#define IDC_EDIT_AIRFOILCL              1298
#define IDC_EDIT_AIRFOILAOA             1299
#define IDC_COMBO_AIRFOILDEFAULTS       1300
#define IDC_STATIC_AIRFOILGRAPH         1301
#define IDC_EDIT_CSAREA                 1302
#define IDC_EDIT_CSDCL                  1303
#define IDC_EDIT_CSREFX                 1304
#define IDC_EDIT_CSREFY                 1305
#define IDC_EDIT_CSREFZ                 1306
#define IDC_COMBO_CSAXIS                1307
#define IDC_EDIT_VCPOSDIRX              1307
#define IDC_EDIT_CSDELAY                1308
#define IDC_EDIT_VCPOSDIRY              1308
#define IDC_COMBO_CSANIM                1309
#define IDC_EDIT_VCPOSDIRZ              1309
#define IDC_COMBO_CSTYPE                1310
#define IDC_EDIT_CSNAME                 1311
#define IDC_BUTTON_CSAMESET             1312
#define IDC_BUTTON_CSDELETE             1313
#define IDC_BUTTON_CSDEFUNDEF           1314
#define IDC_BUTTON_CSPASTEV             1315
#define IDC_BUTTON_VCPOSOFSSET          1316
#define IDC_CHECK_MSHVISEXT             1317
#define IDC_BUTTON_VCPOSDIRSET          1317
#define IDC_BUTTON_VCHUDSIZESET         1317
#define IDC_CHECK_MSHVISCOC             1318
#define IDC_CHECK_DOCKJETT              1319
#define IDC_CHECK_MSHVISVC              1319
#define IDC_BUTTON_CAMXP                1320
#define IDC_CHECK_MSHVISEXTPASS         1320
#define IDC_BUTTON_CAMXM                1321
#define IDC_BUTTON_CAMYP                1322
#define IDC_BUTTON_CAMYM                1323
#define IDC_BUTTON_CAMZP                1324
#define IDC_BUTTON_CAMZM                1325
#define IDC_EDIT_CAMNAME                1326
#define IDC_BUTTON_CAMNAMESET           1327
#define IDC_EDIT_CAMPOSX                1328
#define IDC_EDIT_CAMPOSY                1329
#define IDC_EDIT_CAMPOSZ                1330
#define IDC_BUTTON_CAMPOSSET            1331
#define IDC_EDIT_CAMDIRX                1332
#define IDC_EDIT_CAMDIRY                1333
#define IDC_EDIT_CAMDIRZ                1334
#define IDC_BUTTON_CAMDIRSET            1335
#define IDC_EDIT_CAMTILT                1336
#define IDC_BUTTON_CAMTILTSET           1337
#define IDC_BTN_CAMPASTEV               1338
#define IDC_BUTTON_DELETECAM            1339
#define IDC_BUTTON_CAMTEST              1340
#define IDC_CHECK_FOLLWOMESUPERPREC     1341
#define IDC_EDIT_VCPOSNAME              1342
#define IDC_BUTTON_VCPOSNAMESET         1343
#define IDC_EDIT_VCPOSOFSX              1344
#define IDC_EDIT_VCPOSOFSY              1345
#define IDC_EDIT_VCPOSOFSZ              1346
#define IDC_BUTTON_VCPOSPASTEV          1347
#define IDC_BUTTON_VCPOSCHECK           1348
#define IDC_BUTTON_VCPOSDELETE          1349
#define IDC_CHECK_VCHUDENABLE           1350
#define IDC_EDIT_VCHUDSIZE              1351
#define IDC_CHECK_VCMFDBC               1351
#define IDC_COMBO_VCHUDMESH             1352
#define IDC_COMBO_VCHUDGRP              1353
#define IDC_BUTTON_VCHUDCHECK           1354
#define IDC_EDIT_VCHUDCX                1355
#define IDC_EDIT_VCHUDCY                1356
#define IDC_EDIT_VCHUDCZ                1357
#define IDC_BUTTON_VCHUDCSET            1358
#define IDC_BUTTON_VCHUDPASTEV          1359
#define IDC_EDIT_VCMFDMNUX              1360
#define IDC_EDIT_VCMFDMNUY              1361
#define IDC_EDIT_VCMFDMNUZ              1362
#define IDC_EDIT_VCMFDTLX               1363
#define IDC_EDIT_VCMFDTLY               1364
#define IDC_EDIT_VCMFDTLZ               1365
#define IDC_BUTTON_VCMFDTLPASTEV        1367
#define IDC_EDIT_VCMFDBLX               1368
#define IDC_EDIT_VCMFDBLY               1369
#define IDC_EDIT_VCMFDBLZ               1370
#define IDC_EDIT_VCMFDTRX               1371
#define IDC_EDIT_VCMFDTRY               1372
#define IDC_EDIT_VCMFDTRZ               1373
#define IDC_BUTTON_VCMFDCOLSET          1374
#define IDC_BUTTON_VCMFDTRPASTEV        1375
#define IDC_EDIT_VCMFDBRX               1376
#define IDC_EDIT_VCMFDBRY               1377
#define IDC_EDIT_VCMFDBRZ               1378
#define IDC_BUTTON_VCMFDBLPASTEV        1379
#define IDC_EDIT_VCMFDNAME              1380
#define IDC_BUTTON_VCMFDDELETE          1381
#define IDC_BUTTON_VCMFDCHECK           1382
#define IDC_COMBO_VCMFDMESH             1383
#define IDC_COMBO_VCMFDGRP              1384
#define IDC_EDIT_VCMFDPWRX              1385
#define IDC_EDIT_VCMFDPWRY              1386
#define IDC_EDIT_VCMFDPWRZ              1387
#define IDC_BUTTON_VCMFDPWRPASTEV       1388
#define IDC_BUTTON_VCMFDPWRSET          1389
#define IDC_CHECK_VCMFDPWRSET           1390
#define IDC_BUTTON_VCMFDMNUPASTEV       1391
#define IDC_EDIT_BCNNAME                1391
#define IDC_BUTTON_VCMFDBRPASTEV        1392
#define IDC_BUTTON_BCNNAMESET           1392
#define IDC_COMBO_BCNSHAPE              1393
#define IDC_EDIT_BCNPOSX                1394
#define IDC_EDIT_BCNPOSY                1395
#define IDC_EDIT_BCNPOSZ                1396
#define IDC_BUTTON_BCNPOSSET            1397
#define IDC_BUTTON_BCNPASTEV            1398
#define IDC_EDIT_BCNCOLR                1399
#define IDC_EDIT_BCNCOLG                1400
#define IDC_EDIT_BCNCOLB                1401
#define IDC_BUTTON_BCNCOLSET            1402
#define IDC_EDIT_BCNSIZE                1403
#define IDC_EDIT_BCNFALLOFF             1404
#define IDC_EDIT_BCNPERIOD              1405
#define IDC_EDIT_BCNDURATION            1406
#define IDC_EDIT_BCNTOFS                1407
#define IDC_BUTTON6                     1408
#define IDC_BUTTON_BCNDEL               1408
#define IDC_BUTTON_BCNTOGGLE            1409
#define IDC_BUTTON_BCNSIZESET           1410
#define IDC_BUTTON_BCNFALLOFFSET        1411
#define IDC_BUTTON_BCNPERIODSET         1412
#define IDC_BUTTON_BCNDURATIONSET       1413
#define IDC_BUTTON_BCNTOFSSET           1414

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1410
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
