//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da StationBuilder1.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG_MESH                 103
#define IDD_DIALOG_FOLLOWME             105
#define IDD_DIALOG_DOCK                 106
#define IDD_DIALOG_ANIM                 107
#define IDD_DIALOG_ANIMCOMP             108
#define IDD_DIALOG_ATT                  109
#define IDC_TREE1                       1001
#define IDC_SPIN_POSZ_S                 1005
#define IDC_SPIN_POSZ_L                 1006
#define IDC_SPIN_POSY_S                 1007
#define IDC_EDIT_MESHNAME               1008
#define IDC_BUTTON_LOADMESH             1009
#define IDC_EDIT_POSX                   1010
#define IDC_EDIT_POSY                   1011
#define IDC_EDIT_POSZ                   1012
#define IDC_SPIN_POSY_L                 1014
#define IDC_SPIN_POSX_S                 1015
#define IDC_SPIN_POSX_L                 1016
#define IDC_BUTTON_POS_SET              1017
#define IDC_CHECK_HIGHLIGHT_MSH         1019
#define IDC_EDIT_DIRX                   1020
#define IDC_EDIT_DIRY                   1021
#define IDC_EDIT_DIRZ                   1022
#define IDC_BUTTON_DIR_SET              1027
#define IDC_EDIT_ROTX                   1028
#define IDC_EDIT_ROTY                   1029
#define IDC_EDIT_ROTZ                   1030
#define IDC_BUTTON_ROT_SET              1031
#define IDC_EDIT_GETANGLE               1038
#define IDC_STATIC_MSH1                 1039
#define IDC_STATIC_MSH2                 1040
#define IDC_STATIC_MSH3                 1041
#define IDC_STATIC_MSH4                 1042
#define IDC_STATIC_MSH5                 1043
#define IDC_STATIC_MSH6                 1044
#define IDC_STATIC_MSH7                 1045
#define IDC_STATIC_MSH8                 1046
#define IDC_STATIC_MSH9                 1047
#define IDC_STATIC_MSH10                1048
#define IDC_STATIC_MSH11                1049
#define IDC_STATIC_MSH12                1050
#define IDC_STATIC_MSH13                1051
#define IDC_STATIC_MSH14                1052
#define IDC_STATIC_MSH15                1053
#define IDC_BUTTON_DELETEMESHDEF        1054
#define IDC_SPIN_ROLL                   1056
#define IDC_SPIN_PITCH                  1057
#define IDC_BUTTON_ADD                  1057
#define IDC_SPIN_YAW                    1058
#define IDC_EDIT_FMPOS                  1058
#define IDC_EDIT_FMDIR                  1059
#define IDC_EDIT_ROT                    1060
#define IDC_EDIT_FMROT                  1060
#define IDC_SLIDER_FMSPEED              1061
#define IDC_SPIN_FMX                    1062
#define IDC_SPIN_FMY                    1063
#define IDC_SPIN_FMZ                    1065
#define IDC_SPIN_FMYAW                  1066
#define ID_COPY                         1068
#define ID_COPYVS                       1068
#define ID_EXIT                         1069
#define IDC_SPIN_FMPITCH                1070
#define IDC_SPIN_FMROLL                 1071
#define IDC_SPIN2                       1073
#define IDC_FMRESET                     1078
#define IDC_BTN_MESHPASTEV              1079
#define IDC_EDIT_DOCKPOSX               1080
#define IDC_EDIT_DOCKPOSY               1081
#define IDC_EDIT_DOCKPOSZ               1082
#define IDC_EDIT_DOCKDIRX               1083
#define IDC_EDIT_DOCKDIRY               1084
#define IDC_EDIT_DOCKDIRZ               1085
#define IDC_EDIT_DOCKROTX               1086
#define IDC_EDIT_DOCKROTY               1087
#define IDC_EDIT_DOCKROTZ               1088
#define IDC_SPIN_DOCKPITCH              1090
#define IDC_SPIN_DOCKYAW                1091
#define IDC_SPIN_DOCKROLL               1092
#define IDC_BUTTON_DELETEDOCKDEF        1093
#define IDC_BTN_DOCKPASTEV              1094
#define IDC_SPIN_DOCKPOSX               1095
#define IDC_SPIN_DOCKPOSY               1096
#define IDC_SPIN_DOCKPOSZ               1097
#define IDC_BUTTON_DOCKPOS_SET          1098
#define IDC_BUTTON_DOCKDIR_SET          1099
#define IDC_BUTTON_DOCKROT_SET          1100
#define IDC_CHECK_HIGHLIGHT_DOCK        1101
#define IDC_EDIT_DOCKNAME               1102
#define IDC_COMBO_ANIMTYPE              1108
#define IDC_EDIT_ANIMDURATION           1109
#define IDC_EDIT_ANIMDEFSTATE           1110
#define IDC_EDIT_ANIMNAME               1111
#define IDC_COMBO_ANIMKEY               1112
#define IDC_BUTTON_ANIMDELETE           1113
#define IDC_BUTTON_ANIMADDCOMPROT       1114
#define IDC_BUTTON_ANIMDURATIONSET      1115
#define IDC_BUTTON_ANIMDEFSTATESET      1116
#define IDC_LIST_ANIMCOMPGRPSTOPICK     1117
#define IDC_BUTTON_ANIMNAMESET          1118
#define IDC_LIST_ANIMCOMPGRPSINANIM     1118
#define IDC_EDIT_ANIMNCOMPS             1119
#define IDC_BUTTON_ANIMADDCOMPTR        1120
#define IDC_BUTTON_ANIMADDCOMPSC        1121
#define IDC_EDIT_ANIMCOMPS0             1122
#define IDC_BUTTON_ANIMTESTANIM         1122
#define IDC_EDIT_ANIMCOMPS1             1123
#define IDC_COMBO_ANIMCOMPPARENT        1124
#define IDC_EDIT_ANIMCOMPTYPE           1125
#define IDC_EDIT_ANIMCOMPREFX           1126
#define IDC_EDIT_ANIMCOMPREFY           1127
#define IDC_EDIT_ANIMCOMPREFZ           1128
#define IDC_SLIDER_ANIMTEST             1129
#define IDC_COMBO_ANIMCOMPMESH          1129
#define IDC_BUTTON_ANIMCOMPSETGRPS      1130
#define IDC_EDIT_ANIMCOMPAXISX          1131
#define IDC_BUTTON_ANIMCOMPS0SET        1132
#define IDC_BUTTON_ANIMCOMPS1SET        1133
#define IDC_BUTTON_ANIMCOMPBACKGRPS     1134
#define IDC_EDIT_ANIMCOMPAXISY          1135
#define IDC_EDIT_ANIMCOMPAXISZ          1136
#define IDC_EDIT_ANIMCOMPANGLE          1137
#define IDC_BUTTON_ANIMCOMPREFSET       1138
#define IDC_BUTTON_ANIMCOMPAXISSET      1139
#define IDC_BUTTON_ANIMCOMPANGLESET     1140
#define IDC_BUTTON_ANIMCOMPPASTEV       1141
#define IDC_STATIC_ACREF                1142
#define IDC_STATIC_ACAX                 1143
#define IDC_STATIC_ACANGLE              1144
#define IDC_EDIT_ANIMCOMPNAME           1145
#define IDC_BUTTON_ANIMCOMPNAMESET      1146
#define IDC_BUTTON_ANIMCOMPDEL          1147
#define IDC_CHECK_ATTPARENT             1148
#define IDC_BUTTON_ANIMCOMPTIPSET       1148
#define IDC_CHECK_ATTHIGHLIGHT          1149
#define IDC_EDIT_ATTPOSX                1150
#define IDC_EDIT_ATTPOSY                1151
#define IDC_EDIT_ATTPOSZ                1152
#define IDC_BUTTON_ATTPOS_SET           1153
#define IDC_EDIT_ATTDIRX                1154
#define IDC_EDIT_ATTDIRY                1155
#define IDC_EDIT_ATTDIRZ                1156
#define IDC_BUTTON_ATTDIR_SET           1157
#define IDC_EDIT_ATTROTX                1158
#define IDC_EDIT_ATTROTY                1159
#define IDC_EDIT_ATTROTZ                1160
#define IDC_BUTTON_ATTROT_SET           1161
#define IDC_BTN_ATTPASTEV               1162
#define IDC_SPIN_ATTPITCH               1163
#define IDC_SPIN_ATTYAW                 1164
#define IDC_SPIN_ATTROLL                1165
#define IDC_BUTTON_CRDELATTDEF          1166
#define IDC_EDIT_ATTID                  1167
#define IDC_SPIN_ATTPOSX                1168
#define IDC_SPIN_ATTPOSY                1169
#define IDC_SPIN_ATTPOSZ                1170
#define IDC_STATIC_ANIMCOMPGRPS         1171
#define IDC_EDIT_ATTRANGE               1171
#define IDC_CHECK_ANIMCOMPARMTIP        1172
#define IDC_BUTTON_ATTROT_SET2          1172
#define IDC_BUTTON_ATTRANGESET          1172
#define IDC_LIST_ANIMCOMPATTS           1173

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
